version: '3.3'
services:

  eureka-service:
    build: 
      context: EurekaService
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - cloud


  zuul-service:
    build:
      context: ZuulService
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - eureka-service
    networks:
      - cloud

  cat-service:
    build:
      context: CatsService
      dockerfile: Dockerfile
    depends_on:
      - eureka-service
      - zuul-service
    networks:
      - cloud

  user-service:
    build:
      context: UsersInfoService
      dockerfile: Dockerfile
    depends_on:
      - eureka-service
      - zuul-service
    networks:
      - cloud

  country-service:
    build:
      context: CountriesService
      dockerfile: Dockerfile
    depends_on:
      - eureka-service
      - zuul-service
    networks:
      - cloud

networks:
  cloud:
    external: false